<?php

declare(strict_types=1);

use AIArmada\Docs\Enums\DocStatus;
use AIArmada\Docs\Enums\DocType;
use AIArmada\Docs\Models\Doc;
use AIArmada\Docs\Services\DocumentService;
use AIArmada\Docs\Services\SequenceManager;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

beforeEach(function (): void {
    $this->sequenceManager = new SequenceManager();
    $this->service = new DocumentService($this->sequenceManager);
});

test('can create a document', function (): void {
    $data = [
        'issue_date' => now(),
        'currency' => 'USD',
        'items' => [
            [
                'quantity' => 2,
                'unit_price' => 100,
                'tax_amount' => 10,
            ],
        ],
    ];

    $doc = $this->service->create(DocType::Invoice, $data);

    expect($doc)
        ->toBeInstanceOf(Doc::class)
        ->doc_number->not->toBeNull() // Generated by real sequence
        ->doc_type->toBe(DocType::Invoice->value)
        ->status->toBe(DocStatus::DRAFT)
        ->subtotal->toBe('200.00')
        ->tax_amount->toBe('10.00')
        ->total->toBe('210.00');

    // Verify version created
    expect($doc->versions)->toHaveCount(1);
    expect($doc->versions->first()->change_summary)->toBe('Initial creation');
});

test('can update a document', function (): void {
    $doc = Doc::factory()->create([
        'doc_number' => 'INV-OLD',
        'subtotal' => 100,
        'total' => 110,
    ]);

    $data = [
        'notes' => 'Updated notes',
        'items' => [
            [
                'quantity' => 1,
                'unit_price' => 200,
                'tax_amount' => 20,
            ],
        ],
    ];

    $updatedDoc = $this->service->update($doc, $data);

    expect($updatedDoc->fresh())
        ->notes->toBe('Updated notes')
        ->subtotal->toBe('200.00')
        ->total->toBe('220.00');

    // Verify new version created
    expect($doc->versions)->toHaveCount(1); // Factory might not create one, service creates one
    expect($doc->versions->last()->change_summary)->toBe('Document updated');
});

test('can calculate totals', function (): void {
    $items = [
        [
            'quantity' => 2,
            'unit_price' => 50,
            'tax_amount' => 5,
        ],
        [
            'quantity' => 1,
            'unit_price' => 100,
            'tax_amount' => 10,
        ],
    ];

    $totals = $this->service->calculateTotals($items, 10); // 10 discount

    // Subtotal: (2*50) + (1*100) = 200
    // Tax: (2*5) + (1*10) = 15 (assuming tax_amount is per-line total tax)
    // Total: 200 + 15 - 10 = 205

    expect($totals['subtotal'])->toBe(200.0)
        ->and($totals['tax_amount'])->toBe(15.0)
        ->and($totals['total'])->toBe(205.0);
});

test('can record payment', function (): void {
    $doc = Doc::factory()->create([
        'total' => 100,
        'status' => DocStatus::SENT,
    ]);

    $payment = $this->service->recordPayment($doc, [
        'amount' => 50,
        'payment_method' => 'bank_transfer',
        'reference' => 'REF123',
    ]);

    expect($payment->amount)->toBe('50.00');
    expect($doc->fresh()->status)->toBe(DocStatus::PARTIALLY_PAID);

    // Pay remaining
    $this->service->recordPayment($doc, [
        'amount' => 50,
        'payment_method' => 'bank_transfer',
    ]);

    expect($doc->fresh()->status)->toBe(DocStatus::PAID);
});

test('can clone a document', function (): void {
    $original = Doc::factory()->create([
        'doc_type' => DocType::Invoice,
        'currency' => 'USD',
        'items' => [['name' => 'Item 1']],
    ]);

    $clone = $this->service->clone($original);

    expect($clone->currency)->toBe('USD')
        ->and($clone->doc_number)->not->toBe($original->doc_number)
        ->and($clone->metadata['cloned_from'])->toBe($original->id);
});

test('can convert a document', function (): void {
    $source = Doc::factory()->create([
        'doc_type' => DocType::Quotation,
        'doc_number' => 'QUO-123',
        'subtotal' => 100,
        'total' => 110,
        'items' => [['name' => 'Item 1', 'quantity' => 1, 'unit_price' => 100]],
    ]);

    $converted = $this->service->convert($source, DocType::Invoice);

    expect($converted)
        ->toBeInstanceOf(Doc::class)
        ->doc_type->toBe(DocType::Invoice->value)
        ->subtotal->toBe('100.00')
        ->total->toBe('100.00')
        ->metadata->toHaveKey('converted_from')
        ->metadata->converted_from->doc_number->toBe('QUO-123');
});
